# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: '$(Build.SourceBranchName)-build$(Rev:#r)'

trigger:
  tags:
    include:
    - v*

pool:
  vmImage: ubuntu-latest

jobs:
- job: build
  displayName: Build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build package'
  
  - script: npm run lint -- --format junit --output-file test-results/lint-results.xml
    displayName: 'Run lint'

  - script: npm run test-src -- --reporter mocha-junit-reporter
    displayName: 'Run tests'

  - task: WhiteSource Bolt@20
    inputs:
      cwd: '$(Build.SourcesDirectory)'
    displayName: 'Check dependencies'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-results/*-results.xml'
      mergeTestResults: true
    displayName: 'Publish test results'

- job: publish
  displayName: Publish
  dependsOn: build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      echo '##[command]execute command: npm version ${{ replace(variables['Build.SourceBranchName'], 'v', '')}}'
      npm version ${{ replace(variables['Build.SourceBranchName'], 'v', '')}}
    displayName: 'Set package version'

  - script: |
      npm install
      npm run build
    displayName: 'Build package'
  
  - task: Npm@1
    inputs:
      command: 'publish'
      workingDir: '$(Build.SourcesDirectory)'
      publishRegistry: 'useFeed'
      publishFeed: '31fa665b-2d2b-412c-bf5a-ced9e931516c/3ac2fd32-8918-41b1-8b80-df59bc60d88a'
    displayName: 'Publish package'
