# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: '$(Build.SourceBranchName)$(Rev:.r)'

trigger:
  tags:
    include:
    - v*

pool:
  vmImage: ubuntu-latest

jobs:
- job: build
  displayName: Build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
  
  - script: npm run lint -- --format junit --output-file test-results/lint-results.xml
    displayName: 'Run lint'

  - script: npm run test-src -- --reporter mocha-junit-reporter
    displayName: 'Run tests'

  - task: WhiteSource Bolt@20
    inputs:
      cwd: '$(Build.SourcesDirectory)'
    displayName: 'Check dependency'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-results/*-results.xml'
      mergeTestResults: true

- job: publish
  displayName: Publish
  dependsOn: build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm git version ${{ replace(variables['Build.SourceBranchName'], 'v', '')}}
      npm install
      npm run build
    displayName: 'npm install and build'
